### ISSUE TITLE
[percy:webdriverio] Could not take DOM snapshot

### ISSUE THREAD

**Issue by splurgeop** [percy/percy-webdriverio#696]
I am using the below node version and other details

@percy/webdriverio": "^2.0.0"
"@percy/cli": "^1.0.0-beta.76"
node: v14.16.1
npm: 7.20.5
@cucumber/cucumber:7.3.1
webdriverio@7.16.16

Issue:  With WDIO,trying to get percy working throws up the error

[percy:webdriverio] Could not take DOM snapshot "test_screenshot" (59928ms)
Below are the verbose logs 

[percy:webdriverio] Could not take DOM snapshot "testing" (59928ms)
[percy:webdriverio] Cannot read property 'element-6066-11e4-a52e-4f735466cecf' of undefined
TypeError: Cannot read property 'element-6066-11e4-a52e-4f735466cecf' of undefined
    at *************\node_modules\devtools\build\utils.js:153:16
    at Array.map (<anonymous>)
    at DevToolsDriver.transformExecuteArgs (********\node_modules\devtools\build\utils.js:152:29)
    at DevToolsDriver.executeScript (**********\node_modules\devtools\build\commands\executeScript.js:29:179)
    at Browser.wrappedCommand (*******\node_modules\devtools\build\devtoolsdriver.js:102:55)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Browser.wrapCommandFn (*******\node_modules\@wdio\utils\build\shim.js:104:29)
    at Browser.wrapCommandFn (************\node_modules\@wdio\utils\build\shim.js:104:29)
    at ************\node_modules\@percy\webdriverio\index.js:26:34
    at Browser.wrapCommandFn (**********\node_modules\@wdio\utils\build\shim.js:104:29) (1ms)

Command to run the Percy Tests:

npx percy exec --verbose -- wdio dist\config\wdio.conf.js

I am using WDIO with Devtools protocol

**Comment by splurgeop** [comment]
This is good for closure.
Issue resolved.
